### ISSUE TITLE
comparison between two condition (label_compare)

### ISSUE THREAD

**Issue by DoYup** [jcapelladesto/geoRge#8]
Dear Jordi

Thanks for your help the other day.

I have question on Welch's ttest between different condition. Because my own data is not working I have tried it with example data "mtbl231". But I was not able to have p value and fold change between two condition. 

Here is the script I am using. I have tried it with different combination of control.con = (e.g.  "05mM_Nor)

> s4 <- label_compare(geoRgeR = s2, XCMSet = xset3, ppm.s = NULL,rt.win.min = 1, control.cond = NULL, fc.vs.Control = 1, p.value.vs.Control = 0.05, Show.bp = T)

> str(s4)
'data.frame':   1105 obs. of  5 variables:
 $ Comparison      : Factor w/ 2 levels "","Base peak": 2 1 2 1 1 2 1 2 1 1 ...
 $ X05mM_Normo_MEAN: num  61.89 38.11 81.43 7.36 11.21 ...
 $ X25mM_Normo_MEAN: num  67.12 32.88 82.01 7.92 10.07 ...
 $ X05mM_Normo_SD  : num  7.17 7.17 1.6 0.37 1.92 ...
 $ X25mM_Normo_SD  : num  0.87 0.87 0.723 0.437 1.142 ...

Here is the file name that I downloaded for mtbl231
CELL_Glc12_05mM_Normo_04
CELL_Glc12_05mM_Normo_05
CELL_Glc12_05mM_Normo_06
CELL_Glc12_25mM_Normo_16
CELL_Glc12_25mM_Normo_17
CELL_Glc12_25mM_Normo_18
CELL_Glc13_05mM_Normo_01
CELL_Glc13_05mM_Normo_02
CELL_Glc13_05mM_Normo_03
CELL_Glc13_25mM_Normo_13
CELL_Glc13_25mM_Normo_14
CELL_Glc13_25mM_Normo_15

Thanks in advance.

**Comment by jcapelladesto** [comment]
Dear DoYup,

Thank you for contacting again.
First, I am aware that `label_compare` does not return p-values and foldchanges as `PuInc_seeker` does. I will try to add this feature to the function ASAP (I actually cannot understand why we did not do that in the first place). 
The main feature of  `label_compare` is the first column ('Comparison') which will include "UP_" or "DOWN_" values when significant results are found. Since I see that when you run 
```
s4 <- label_compare(geoRgeR = s2, XCMSet = xset3, ppm.s = NULL,rt.win.min = 1, control.cond = NULL, fc.vs.Control = 1, p.value.vs.Control = 0.05, Show.bp = T)
```
you have 'ppm.s' and 'control.cond' set to NULL. This might be the cause that this result comes up:
```$ Comparison : Factor w/ 2 levels "","Base peak": 2 1 2 1 1 2 1 2 1 1 ...```
Please try to run again this function, like this (or similar):
```
s4 <- label_compare(geoRgeR = s2, XCMSet =mtbls213, rt.win.min = 1, 
										control.cond = "05mM_Normo",ppm.s=6.5,
										fc.vs.Control = 1, p.value.vs.Control = 0.05, Show.bp = T)
```
This should return (see number of levels of $ Comparison):
```
str(s4)
'data.frame':	1105 obs. of  5 variables:
 $ Comparison      : Factor w/ 4 levels "","Base peak",..: 2 1 2 1 1 2 1 2 1 1 ...
 $ X05mM_Normo_MEAN: num  61.89 38.11 81.43 7.36 11.21 ...
 $ X25mM_Normo_MEAN: num  67.12 32.88 82.01 7.92 10.07 ...
 $ X05mM_Normo_SD  : num  7.17 7.17 1.6 0.37 1.92 ...
 $ X25mM_Normo_SD  : num  0.87 0.87 0.723 0.437 1.142 ...
```

Last but not least, you indicated that this function does not work for your data. I would like to ask you if at least the % values are calculated.

Yours sincerely,

Jordi

**Comment by DoYup** [comment]
Great. It works.

For my data, % are calculated. I wish to see p value and fold change soon.  :)
Now I will try to do it with my data. (I may return to you at that  moment with question)
Thank you again

**Comment by vivekmishra8739** [comment]
How to get result after running the function?

**Comment by jcapelladesto** [comment]
The package was updated a few weeks ago, the p-value and fold-change should be reportable now. I wonder if you have been able to run it for your data.

**Comment by DoYup** [comment]
Hi Jordi

It sounds great! And it works very well with my real data thanks to your
help !!!

Sincerely,
Do Yup
